name: dhis2_flutter_ui
description: "A new Flutter package project."
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.10+1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geolocator_android: 4.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  assets:
    - assets/icons/
