name: dhis2_flutter_ui
description: This is Dhis2 flutter ui components used in Hisp Tanzania.
version: 1.0.2
repository: https://github.com/hisptz/dhis2-flutter-ui

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  geolocator: ^8.2.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_test_ui: ^2.0.0


flutter: